project_id = "pciamhfhilopdkuhzyfs"

[functions.check-admin-email]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.get-invoice-url]
verify_jwt = false

[functions.place-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-magic-link-email]
verify_jwt = false

[functions.create-design-payment]
verify_jwt = false

[functions.verify-design-payment]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false
