project_id = "mumouyiaegzihctyyijf"

[functions.check-admin-email]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.get-invoice-url]
verify_jwt = false

[functions.place-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
