project_id = "mumouyiaegzihctyyijf"

[functions.create-razorpay-order]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.get-invoice-url]
verify_jwt = false

[functions.place-order]
verify_jwt = false

